
services:
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./data:/app/data
      - ./backend/.env:/app/backend/.env
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: .
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  data: 